name: Publish Porthunter
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Publish Porthunter
        env:
          APIKEY: ${{ secrets.APIKEY }}
        run: ./publishPorthunter.ps1
        shell: pwsh
