name: Publish Porthunter
on: [workflow_dispatch]

jobs:
  build:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v1
    - name: Publish
    env:
       APIKEY: ${{secrets.apiporthunter}}
      run: ./publish.ps1
      shell: pwsh