name: Publish Porthunter
on: [workflow_dispatch]

jobs:
    build:
      name: Publish
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - name: Publish Porthunter
          env:
            apiporthunter: ${{ secrets.apiporthunter }}
          run: .\.github\workflows\publishPorthunter.ps1
          shell: pwsh